### ISSUE TITLE
Damaged Small Craft Thruster Shown As Avionics Repair

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#151]
As per title, attached image of the affected small craft. Campaign file attached. There are 4 small crafts with the same error, basically all the thruster repairs.

![damagedsmallcraftthrustershownasavionicsrepair](https://cloud.githubusercontent.com/assets/17064665/18243695/d1881588-738e-11e6-969c-675996d05c8e.png)

[DamagedSmallCraftThrusterShownAsAvionicsRepair.7z.txt](https://github.com/MegaMek/mekhq/files/454735/DamagedSmallCraftThrusterShownAsAvionicsRepair.7z.txt)

**Comment by BLOODWOLF333** [comment]
I see this in my campaign ass well.  When GM adding one of every part for a starting stockpile thrusters just added another avionics system part.  Didnt know if that was right not so went with it.

**Comment by neoancient** [comment]
This is actually a combination of two different issues: the avionics repair shows up because of a bug in GM > Restore ( #146 ), which has been fixed, and the thrusters fail to appear as an eligible repair because thrusters were not showing as a part needing repair except when installed in Dropship, Jumpships, or Warships.

**Comment by mkerensky** [comment]
This wasn't quite fixed, it turns out.  I just found (0.43.4 daily) a reference in the thruster part where a replacement pulled in a missing avionics part instead of a thruster part. This will be fixed in a PR I'm working on.
