### ISSUE TITLE
CO Rating showing tech shortage due to infantry

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#215]
In IntOpsRep java under `calcTechSupportValue()` line 600

It looks like infantry and protomechs are supposed to fall under GeneralTechTeams but when looping over the tech skills I don't see what would fall into the last else which add +1 to general.

On line 650 the condition for `if ((getProtoTechTeamsNeeded() + getInfantryTechTeamsNeeded()) > getGeneralTechTeams())` will always be true and cause a tech shortage.

I have a temporary fix for it ready that just comments out lines 650-652. It should suffice until infantry and protomech specific techs are added.

**Comment by dericpage** [comment]
The real issue here is that MHQ doesn't support Infantry or Protomech techs.  The idea of 'general' techs is there in case those (or other) tech types eventually get added, they will get counted until they can be dealt with in a specific fashion.  There's a note in the details of the unit rating report explaining this (somewhat).

Taking infantry and protos out of the techShortage calculation is probably okay but one of these days we really need to get around to tracking infantry and proto techs (and proto support in general).

**Comment by Dylan-M** [comment]
I'm not okay with it being lumped in with a proper fix pull request however. They need to be separate PRs, and honestly instead of just commenting them out, we should offer users an _option_ to ignore them for now. As such, I'm marking the PR as invalid and not accepted.

**Comment by neoancient** [comment]
According to StratOps, p. 168 protos are maintained by 'Mech techs and conventional infantry by mechanics.

**Comment by dericpage** [comment]
So it does.  I could have sworn they were supposed to be a different specialty (at least for protos) but apparently not.  I'll create a new branch for this one.  Should be easy to fix, but I might not get to it until this weekend as I'll need to re-read that section to make sure I haven't screwed up anything else.

**Comment by purpledragon2** [comment]
Oh, ok, I had a suggestion for infantry, but it looks like it has been answered already.  Basically, if you'd like to make it an option, my suggestion was to make the doctors the techs for infantry.

**Comment by dericpage** [comment]
I'm going to go by the official rules for Campaign Ops.  I think part of my confusion came from the fact that FMM(r) Dragoons Rating doesn't require tech support for Infantry (only Medical and Admin) and doesn't account for Protomechs at all.

**Comment by dericpage** [comment]
I just uploaded a new pull request that should take care of the issue.  I'll give it a few days for folks to look over before I merge it in.

**Comment by Dylan-M** [comment]
Fixed with a2703d5702e357b12f495073d80c61d6e5dceaee

**Comment by pheonixstorm** [comment]
Not completely fixed. Maybe.
First, should I be able to assign a mechanic to infantry units?

Second, something else in the mechanic count is off. In testing for ticket #220 the needed mechanics for 6 platoons was correct at 2. In the campaign I have been preparing I have 6 platoons with 36 vehicles and 3 VTOLs, the total mechanics should have been 41 but the count displayed is 40. Not sure if its just a glitch or a bug. No errors in the log though. Log for now, will post the campaign and customs later

[mechanic log.txt](https://github.com/MegaMek/mekhq/files/566363/mechanic.log.txt)

**Comment by dericpage** [comment]
1. The Unit Rating only cares if you have enough mechanic teams.  It doesn't care about their explicit assignments.

2. The code for determining the number of mechanics needed to support infantry doesn't go by platoon count (since platoon size varies) but rather by trooper count.  It's 1 mechanic per 112 troopers, rounding half up.  So, if any of those 6 platoons are fewer than 28 troopers, that would explain the difference.

**Comment by pheonixstorm** [comment]
The first was unrelated to the rating itself. I was more curious as to if we should be able to assign techs to infantry for maintenance purposes.

As for the second, that makes some sense. In the campaign I referenced though it is 3 platoons of jump infantry and 3 platoons of motorized infantry which counted up would still require 2 mechanics.

Here is the campaign with 2 custom infantry.
[campaigns.zip](https://github.com/MegaMek/mekhq/files/567476/campaigns.zip)

**Comment by dericpage** [comment]
Your jump platoons are only 3 squads of 7 for 21 troopers.
Your motoroized platoons are 4 squads of 7 for 28 troopers.
Total number of troopers = (3 * 21) + (3 * 28) = 147.
Number of mechanic teams needed = 147 / 112 = 1.3125, which rounds down to 1.

**Comment by pheonixstorm** [comment]
Works for me. One issue settled, a few more to go. Have another report to make that I need to build a new campaign for.
