### ISSUE TITLE
[0.49.7 build 657] MML starter missing again

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3101]
Sorry, this is #2974  again, but this time in the latest build. 

mml-startup is missing in 0.49.7 nightly build 657

**Comment by Windchild292** [comment]
I have no idea as to why this has returned, as exact same code is working for the other two.

**Comment by Windchild292** [comment]
I've fixed this in the latest build.

**Comment by kernhe** [comment]
May I object? ... in 0.49.8-686 the lab starter (at least for linux) is still not present.

**Comment by Windchild292** [comment]
Investigating yet again...

**Comment by Windchild292** [comment]
It may be because of issues we've been having with what I believe to be caching since the MML directory rework nearly two weeks ago. Our internal build scripts are now largely standardized for all three projects, and the code in question duplicates that we use for MM exactly.

**Comment by kernhe** [comment]
Now starters are there, but be have the same files and folders missing as mentioned in #3083 

In data missing:
- folder boards
- folder forcegenerator
- folder mapsetup
- folder mechfiles
- folder scenarios
- files: canonUnitQuirks.xml
- files: unitQuirksSchema.xsd
- files: unit_roles.txt

For clarity: I download the file: mhq-release-win-temurin-jdk11.zip from the github actions when marked with a green checkmark. Then I decompress mekhq-0.49.8-SNAPSHOT.zip...  and normally everything is fine. Did I miss something?


Should the build be seperated: 
- executables and libs for win, mac, nix
- universal data
... so we can update those independently? Or just keep it as it is .-)

**Comment by Windchild292** [comment]
This is apparently fixed without me doing anything.

As for the separation... it's too much work to do currently.
