### ISSUE TITLE
[ATB] 3.25 : Enemy reinforcements incorrectly set to deploy at the start of the game

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#40]
If you load the campaign save and try to play the base attack mission, you can see that the jade falcon reinforcements deploy at the start of the game, instead of deploying a few turns into the game (as they should). This seems to happen randomly for some missions where the reinforcements aren't actually reinforcements.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/196863/battletech.zip)

**Comment by neoancient** [comment]
Fixed in f0badc4

**Comment by Question2** [comment]
[#battletech.zip](https://github.com/MegaMek/mekhq/files/254817/battletech.zip)

This is still happening for me in 3.27, the latest scenario has the reinforcements deploying at the start of the game.

**Comment by neoancient** [comment]
3.27 predates this fix.
