### ISSUE TITLE
[0.50.01 Nightly] SPAs with prerequisites referencing skills from before terminology change do not appear as selectable on qualifying personnel. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4991]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

SPAs imported with settings from before the Mek/Mech terminology change do not show up on on personnel if they include prerequisites that involve impacted terms. There is a handler that is correctly changing the label in the options screen, but it does not seem to actually enable them.

Below: this pilot should qualify for the Human TRO SPA, yet it does not show. 
![image](https://github.com/user-attachments/assets/49a5f4ba-16a8-40e3-b67c-4f6160206cea)
![image](https://github.com/user-attachments/assets/b799de1e-f2f8-4ad8-a0b0-98bf7b551aaf)
![image](https://github.com/user-attachments/assets/0585142e-c3c0-4a9b-9ef0-67a97d066580)

This can be fixed by manually removing and re-applying the prerequisite, or by save editing the terminology. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1-SNAPSHOT - Rev. 036d7bea06aa05b4e65424baa02bf8b67d5c78f3

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17266944/mekhq.log)
[1st Rimward HussarsCont.zip](https://github.com/user-attachments/files/17266945/1st.Rimward.HussarsCont.zip)
[customs.zip](https://github.com/user-attachments/files/17266946/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by PhoenixHeart512** [comment]
This might be related to https://github.com/MegaMek/mekhq/issues/4912 ? If so it should be fixed in the latest Nightly

**Comment by Tzahr** [comment]
Still happens in my save as of today's Nightly. 
Checking my savegame, the SPA section notices all the relevant skills as still being "Mech". I'm going to try and manually edit the prerequisities to see if that helps.

**Comment by Tzahr** [comment]
Yep, manually altering Mech -> Mek in the SPA section of my saves restored full SPA function.
Whatever compatibility handler is supposed to handle these isn't working correctly.

**Comment by IllianiCBT** [comment]
Yeah, it looks like some wires got crossed with the PR that _should_ have fixed that. As, checking the changes made, I can see that my compatibility changes are simply not there. That can sometimes happen if I'm bouncing back and forth between branches a lot - which I was at the time.

**Comment by IllianiCBT** [comment]
Closing as resolved
